### ISSUE TITLE
This should be part of the SUSE organization

### ISSUE THREAD

**Issue by Vogtinator** [suse-projects/source#23]
There is already https://github.com/SUSE which seems like a much better fit than a custom organization.

**Comment by oskapt** [comment]
The organization is how the GitHub pages URL is derived. If we moved it to the SUSE org, it would have to become https://suse.github.io - and that seems a bit aspirational for this site. :)

**Comment by okurz** [comment]
As https://suse.github.io/ already exists redirecting to https://opensource.suse.com/ maybe it makes sense to connect these projects still or make suse-projects a subpage of https://opensource.suse.com/ instead?

**Comment by Vogtinator** [comment]
> The organization is how the GitHub pages URL is derived. If we moved it to the SUSE org, it would have to become https://suse.github.io - and that seems a bit aspirational for this site. :)

It seems like the `sources` repo and the actual page content are in separate repositories anyway, so moving just the `sources` repo to the SUSE org shouldn't make any difference FWICT.
