### ISSUE TITLE
What's the license of this repository?

### ISSUE THREAD

**Issue by Vogtinator** [suse-projects/source#31]
I don't see any license text in this repository. At least for logos copied from the referenced projects, the license has to be clearly visible.

**Comment by oskapt** [comment]
The originating site where I borrowed the look and feel and some of the HTML and CSS from is CC0 - no rights reserved. What license do you think is appropriate here?

**Comment by vestival** [comment]
I'd go for an Apache 2 License :)

**Comment by oskapt** [comment]
I think there are two things to be licensed:

- HTML/CSS - I'm in favor of something like CC0 - there's no magic here, and I don't really care if someone else takes it and uses it. I took most of it from somewhere else, and anyone else can do the same.
- The site content (logos and all the YAML) - this we should probably set a reasonable license on, but I'm open to any suggestions. 

Please include a short statement of why you feel the suggested license is the right choice.

**Comment by Vogtinator** [comment]
> HTML/CSS - I'm in favor of something like CC0 - there's no magic here, and I don't really care if someone else takes it and uses it.

CC0 sounds fine, other common choices are GFDL and CC BY-SA.

> I took most of it from somewhere else, and anyone else can do the same.

What's the license of those original sources? In most cases you can't copy from somewhere and then put it under a different license.

> The site content (logos and all the YAML) - this we should probably set a reasonable license on, but I'm open to any suggestions.

While the YAML probably won't contain anything under copyright (summary should be short enough), the logos definitely are copyrighted. So it's important to keep the original license and copyright statements for those.

**Comment by Vogtinator** [comment]
Any progress here?

**Comment by dcermak** [comment]
Any news here? This repository is currently still "all rights reserved" and contributing is problematic from a legal perspective.

**Comment by Conan-Kudo** [comment]
> The originating site where I borrowed the look and feel and some of the HTML and CSS from is CC0 - no rights reserved. What license do you think is appropriate here?

What was the originating site?

**Comment by oskapt** [comment]
I've brought over License text from [the other site](https://github.com/RedHatOfficial/RedHatOfficial.github.io), though anything we used falls under the MIT and CC0 aspects (which is why no license text was included previously).

I don't know what problems any of you are having with contributing a logo and a link. Doing so doesn't change the ownership of your project. Logos constitute fair use in this context, but you're welcome not to include one. That project just won't ever be featured. 

In any event, all of you seem to understand more about this than I do, so please make _suggestions_ if something needs to be done differently. I'm not trying to step on anyone's little toes - I just want a place where people can put links to their projects.

**Comment by Conan-Kudo** [comment]
It would be helpful if the README (or a separate file) indicated the origin of things you copied over and the licensing from there, as well the licensing of the new/unique content.

**Comment by oskapt** [comment]
> It would be helpful if the README (or a separate file) indicated the origin of things you copied over and the licensing from there, as well the licensing of the new/unique content.

The JavaScript and CSS are CC0 and MIT. No attribution is required. I've added licensing information to the README. If you don't think this is enough, then please submit a PR.

**Comment by Conan-Kudo** [comment]
MIT requires attribution.

**Comment by dcermak** [comment]
Adrian Goins ***@***.***> writes:

> I've brought over License text from [the other
> site](https://github.com/RedHatOfficial/RedHatOfficial.github.io),
> though anything we used falls under the MIT and CC0 aspects (which is
> why no license text was included previously).

Thank you!


> I don't know what problems any of you are having with contributing a logo and a link. Doing so doesn't change the ownership of your project. Logos constitute fair use in this context, but you're welcome not to include one. That project just won't ever be featured. 

It's not so much about contributing a link to a project, but about
reusing this website for other purposes, e.g. to showcase your own
projects. Then one must comply with the licensing terms and that's much
easier if you know them ;-)

> In any event, all of you seem to understand more about this than I do, so please make _suggestions_ if something needs to be done differently. I'm not trying to step on anyone's little toes - I just want a place where people can put links to their projects.

Usually the license texts are put into the repository as
well.

I would also suggest to add a reference to
https://github.com/RedHatOfficial/RedHatOfficial.github.io as the
primary license of that repo is CC-BY-SA (thereby requiring
attribution).

**Comment by oskapt** [comment]
As stated, please submit a PR with the requested changes, and I'll be happy to review it.
