### ISSUE TITLE
Value upstream first over creating new projects

### ISSUE THREAD

**Issue by JanZerebecki** [suse-projects/source#38]
https://github.com/suse-projects/source/pull/17 was rejected with:

> We intentionally want to limit this to projects that SUSE created. Otherwise it will become a list of hundreds of projects where SUSE made any commit, and that changes the value of the page.

Indeed this does change values. Before we valued upstream first ( see https://opensource.suse.com/suse-open-source-policy ) over creation of new projects for the sake of distinct projects. There are situations were it is useful to create new projects even when existing projects could be made to fit. But this goes one step further and generally valuing it more, without inspecting the case. Can you explain what benefit new projects / distinct projects have that makes them more valuable than upstream first?

**Comment by vojtech-pavlik** [comment]
Promoting SUSE's new projects is important for SUSE's image as an innovator. It doesn't imply contributions to existing projects are any less valuable, this is just not the place for them.
