### ISSUE TITLE
Unclear rules for "open source software that SUSE has created"

### ISSUE THREAD

**Issue by okurz** [suse-projects/source#39]
I am wondering if for example we should add projects from https://github.com/os-autoinst/ to this page, e.g. https://github.com/os-autoinst/openQA/ . One reason for hestitation is that I am not sure if we should say that "SUSE has created" openQA. Likely it was mainly if not 100% SUSE colleagues which at that time were IIRC members of a "openSUSE team" so it could be that the creation of the project was actually done by "openSUSE" as an entity, not SUSE. Also, despite the main contributions done by SUSE colleagues there are many contributions by non-SUSE members. I hope this can be clarified in this project here and maybe a disclaimer along the lines of "Listing a project by no means tries to diminuish any contribution regardless if project members are colleagues of SUSE or not". I am sure there can be better phrasing :)

**Comment by oskapt** [comment]
The page exists to show SUSE's contribution to open source, so if the project wasn't created by SUSE as an entity, it shouldn't be here. We could change that to "open source software that SUSE contributed to," but then we're opening the door to hundreds of projects where "contributed to" is of vague value. When the items listed on the page have questionable value, then the whole page has questionable value, and we don't want to create a page with questionable value.

So as it stands right now, I think the goal is to keep it limited to OSS projects that SUSE created.

Let me know if you disagree.
