### ISSUE TITLE
Oredering by project by score / size / number of contributions

### ISSUE THREAD

**Issue by lkocman** [suse-projects/source#54]
Hello team,

Leap or generally openSUSE (Including Tumbleweed) is one of the largest aggregator of opensource work and the largest opensource projects SUSE has.  Yet it didn't make it to the top. What about to put on some score based ordering?

I do not want to be the person to put it into the first row. But contribution wise, it would be the case.
Comming up with some score based ordering could help.

Otherwise I'm happy that its visible without scrolling at least on my computer.

my 2 cents.

**Comment by oskapt** [comment]
Projects are sorted alphabetically, which makes them easy to find. If we sort by other criteria, people will have to dig through a list of what appear to be unordered items to find whatever they're looking for. This page is a collection of resources, and listing them by other criteria turns it into a scoreboard. I'd like to keep it neutral, where no project is better than any other project. 

Hopefully we won't start seeing projects called AAABestProjectEver. 😄
